name: Android GitHub Actions pipeline
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build

  test:
    name: Run Test Suite [Unit, Instrumented]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Execute Unit Tests (gradlew test)
        run: bash ./gradlew test --stacktrace

      - name: Execute Instrumentation Tests (gradlew connectedCheck - api 30)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedCheck --stacktrace

  lint:
    name: Check code style with linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run ktlint
        run: ./gradlew ktlintCheck
